# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gaussian-smoothing',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/gaussian-smoothing',
                'lib_path': 'gaussian_smoothing'},
  'syms': {'gaussian_smoothing.core': {'gaussian_smoothing.core.foo': ('core.html#foo', 'gaussian_smoothing/core.py')}}}
